apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello</title>
    </head>
    <body>
      <h1>Hello World</h1>
    </body>
    </html>
